spring:
  application: # 项目设置
    name: goshop
  mvc: # 配置Spring MVC
    servlet:
      path: /
  datasource: # 配置数据库
    url: jdbc:mysql://120.78.146.199:3306/goshop?characterEncoding=utf-8&time_zone=+8:00
    username: root
    password: 112233789xX@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jackson: # 配置jackson 自动转下划线
    property-naming-strategy: SNAKE_CASE
  redis: # 配置redis
    lettuce:
      pool:
        max-active: 50 # 最大活跃连接数
        min-idle: 0    # 最小等待连接数
        max-idle: 8
    local:
      database: 0
      host: locahost
      port: 6379
      # password:
      timeout: 50
    user:
      database: 1
      host: localhost
      port: 6379
      # password:
      timeout: 50
    shop-car:
      database: 2
      host: localhost
      port: 6379
      # password:
      timeout: 50

# 设置服务器
server:
  port: 8080
  servlet:
    session:
      timeout:

# 配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml

# 分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true




