spring:
  application: # 项目设置
    name: goshop
  mvc: # 配置Spring MVC
    servlet:
      path: /
  datasource: # 配置数据库
    url: jdbc:mysql://localhost:3306/goshop?characterEncoding=utf-8
    username: root
    password: 112233789xX@
    driver-class-name: com.mysql.cj.jdbc.Driver

# 设置服务器
server:
  port: 8080
  servlet:
    session:
      timeout: 30m

#配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
