spring:
  application: # 项目设置
    name: goshop
  mvc: # 配置Spring MVC
    servlet:
      path: /
  datasource: # 配置数据库
    url: jdbc:mysql://localhost:3306/goshop?characterEncoding=utf-8&time_zone=+8:00
    username: root
    password: 112233789xX@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: # 配置jackson 自动转下划线
    property-naming-strategy: SNAKE_CASE
  redis: # 配置Redis
    host: localhost
    database: 0
    port: 6379

# 设置服务器
server:
  port: 8080
  servlet:
    session:
      timeout:

# 配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml

# 分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

# 配置控制台输出
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"




